import Head from "next/head";
import Link from "next/link";
import {
  AppShell,
  SecondaryNav,
  Kpis,
  FilterRow,
  Table,
  CustomViews,
  PageTitle,
} from "components";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-10">
        <Link
          href="/supplier-manager"
          className="block w-fit p-4 font-bold text-blue-700 hover:underline"
        >
          Supplier Manager
        </Link>
        <Link
          href="/table-system"
          className="block w-fit p-4 font-bold text-blue-700 hover:underline"
        >
          Table system
        </Link>
      </main>
    </>
  );
}
