import Head from "next/head";
import { useRef } from "react";
import { AppShell, PageTitle, DataTable } from "components";
import { useIsomorphicLayoutEffect } from "usehooks-ts";
import { gsap } from "gsap-trial";
import ScrollTrigger from "gsap-trial/dist/ScrollTrigger";
gsap.registerPlugin(ScrollTrigger);

export default function Home() {
  const main = useRef(null);
  useIsomorphicLayoutEffect(() => {
    let ctx = gsap.context(() => {
      // const tl = gsap.timeline({
      //   scrollTrigger: {
      //     trigger: "[data-listrow]",
      //     // pin: "[data-header]",
      //     markers: true,
      //     start: "top top",
      //     end: "bottom top",
      //     scroller: "[data-contentPane]",
      //   },
      // });
      // tl.to("[data-header]", {
      //   position: "fixed",
      //   width: "100%",
      //   top: 0,
      // });
      // tl.to("[data-footer]", {
      //   position: "fixed",
      //   width: "100%",
      //   bottom: 0,
      // });
      // const st = ScrollTrigger.create({
      //   trigger: "[data-listrow]",
      //   pin: "[data-header], [data-footer]",
      //   start: "top top",
      //   scroller: "[data-contentpane]",
      // });
      // const tl2 = gsap.timeline({
      //   scrollTrigger: {
      //     trigger: "[data-listrow]",
      //     pin: "[data-footer]",
      //     markers: true,
      //     start: "top top+100px",
      //     scroller: "[data-contentPane]",
      //   },
      // });
    }, main);
    return () => ctx.revert();
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main ref={main}>
        <AppShell>
          <div className="space-y-2xs-xs">
            <PageTitle title="Table system" />
            <DataTable />
          </div>
        </AppShell>
      </main>
    </>
  );
}
