import Head from "next/head";
import {
  AppShell,
  SecondaryNav,
  Kpis,
  FilterRow,
  Table,
  CustomViews,
  PageTitle,
} from "components";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <AppShell>
          <div className="space-y-2xs-xs">
            <PageTitle />
            <SecondaryNav breakP="md" />
            <Kpis />
            <FilterRow />
            <CustomViews />
            <Table />
          </div>
        </AppShell>
      </main>
    </>
  );
}
